config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }

  resource :dashboard, controller: 'dashboard'
  resources :watched_steam_profiles

  root 'dashboard#show'
end

app/models/application_record.rb
# Automatically generated base record class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
# Domain model object to represent Games which have been fetched from Steam
class Game < ApplicationRecord
  has_many :library_entries

  validates :appid, presence: true

  def store_link
    "https://store.steampowered.com/app/#{appid}"
  end
end

app/models/library_entry.rb
# Domain model object to act as a decorated join between SteamProfiles and
# their games
class LibraryEntry < ApplicationRecord
  belongs_to :game
  belongs_to :steam_profile

  scope :recent, lambda {
    where(recently_played: true)
      .order('playtime_in_hours desc')
  }
  scope :favorites, -> { order('playtime_in_hours desc').limit(5) }

  validates :playtime_in_hours, presence: true
  validates :playtime_in_hours, numericality: { only_integer: true }

  delegate :name, to: :game
  delegate :icon_url, to: :game
  delegate :store_link, to: :game
end

app/models/steam_profile.rb
# This class represents a given Steam user's basic metadata.
class SteamProfile < ApplicationRecord
  after_save :update_library

  has_many :games, through: :library_entries
  has_many :library_entries, dependent: :destroy

  validates :steam_id, presence: true
  validates :vanity_name, presence: true
  validates :vanity_name, uniqueness: true

  scope :for_vanity_name, lambda { |vanity_name|
    where('vanity_name = ?', vanity_name)
  }

  # Not quite a scope; this is used to map out the favrite games of a particular
  # profile.
  def favorite_games
    library_entries.favorites.map(&:game)
  end

  # Not quite a scope; this is used to map out the games recently played
  # by this steam_profile based on its relationships
  def recent_games
    library_entries.recent.map(&:game)
  end

  # Updates this SteamProfiles library
  def update_library
    SteamService.update_library_for(self)
  end

  # Setter override to ensure information derived from the SteamAPI is updated
  # whenever the vanity_name is changed.
  def vanity_name=(val)
    self[:vanity_name] = val
    update_steam_id
  end

  private

  # This method, designed to be called on before_create, automatically
  # fetches the steam_id for this profile if one does not exist.
  def update_steam_id
    self.steam_id = SteamService.steam_id_for(vanity_name)
  end
end

app/models/user.rb
# This class represents a user within the system for authentication,
# authorization and interaction purposes.  They are currently the only type
# of acting agent within the system.
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Remember, belongs_to is required:true by default
  belongs_to :steam_profile
  has_many :watched_steam_profiles

  validates :vanity_name, presence: true
  validates :vanity_name, length: { maximum: 254 }

  before_validation :ensure_steam_profile

  delegate :favorite_games, to: :steam_profile
  delegate :library_entries, to: :steam_profile
  delegate :recent_games, to: :steam_profile

  private

  # This method, designed to be called on before_save, automatically
  # associates this user with a SteamProfile (creating one if it does not
  # already exist).
  def ensure_steam_profile
    return true unless vanity_name_changed?
    return false if vanity_name.blank? # This will get caught elsewhere

    self.steam_profile = SteamProfile
                         .find_or_create_by(vanity_name: vanity_name)

    # At this time, the only thing to make a SteamProfile invalid
    # is if it can't find the vanity_name.
    errors.add(:vanity_name, 'was not found.') unless steam_profile.valid?
  end
end

app/models/watched_steam_profile.rb
# This class defines what profiles a given user is watching
class WatchedSteamProfile < ApplicationRecord
  belongs_to :steam_profile
  belongs_to :user

  validates :vanity_name, presence: true
  validate :steam_profile_must_be_valid

  before_validation :ensure_steam_profile

  delegate :favorite_games, to: :steam_profile
  delegate :library_entries, to: :steam_profile
  delegate :recent_games, to: :steam_profile

  private

  # Designed to be called before_validation, this method ensures that the
  # WatchedSteamProfile has an actual steam_profile associated with it.
  def ensure_steam_profile
    return if vanity_name.blank?
    self.steam_profile = SteamProfile.find_or_create_by(
      vanity_name: vanity_name
    )
  end

  # Ensures the validity of the steam profile.  There's literally only
  # one thing that can be set right now, which is the vanity name.  This
  # may need to be expanded in the future.
  def steam_profile_must_be_valid
    return if steam_profile.nil? # This will get caught elsewhere

    unless steam_profile.valid?
      errors.add(:steam_profile, 'Invalid vanity name.')
    end
  end
end

app/controllers/application_controller.rb
# This is the base class for any controllers in the system
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
# This class displays the user's dashboard which contains:
# * The current_user's recent games
# * The current_user's top games
# * The current_user's Watched Friends' information as the same
class DashboardController < ApplicationController
  before_action :authenticate_user!

  # This method is used to setup and display the data for the user's
  # dashboard
  def show
    @steam_profile = current_user.steam_profile
    @favorite_library_entries = current_user.library_entries.favorites
    @recent_library_entries = current_user.library_entries.recent

    @watched_steam_profiles = current_user.watched_steam_profiles
                                          .order('vanity_name ASC')
  end
end

app/controllers/registrations_controller.rb
# Override controller to add further functionality to Devise's standard
# offerings.
class RegistrationsController < Devise::RegistrationsController
  private

  # Returns the custom list of user params.
  # This method simply calls out to sign_up_params, because we actually
  # want both sets to be identical.
  def account_update_params
    sign_up_params
  end

  # Returns the custom list of user params.
  def sign_up_params
    params.require(:user).permit(:email,
                                 :current_password,
                                 :password,
                                 :password_confirmation,
                                 :vanity_name)
  end
end

app/controllers/watched_steam_profiles_controller.rb
# This class handles interfacing for handling a user's watched profiles;
# sort of like a friends list, but I wanted something narrower than my Steam
# friends.
class WatchedSteamProfilesController < ApplicationController
  before_action :authenticate_user!

  def create
    @watched_steam_profile =
      WatchedSteamProfile.new(watched_steam_profile_params)
    @watched_steam_profile.user = current_user

    if @watched_steam_profile.save
      flash[:success] = 'May the stalking continue.'
      return redirect_to dashboard_path
    end

    render :new
  end

  def destroy
    @watched_steam_profile = current_user.watched_steam_profiles
                                         .find(params[:id])

    if @watched_steam_profile.destroy
      flash[:success] = 'No more stalking.  :('
      return redirect_to dashboard_path
    end

    flash[:error] = 'We just couldn\'t stop watching.'
    redirect_to dashboard_path
  end

  def new
    @watched_steam_profile = WatchedSteamProfile.new
  end

  private

  def watched_steam_profile_params
    params.require(:watched_steam_profile).permit(:vanity_name)
  end
end

app/helpers/game_helper.rb
# Helper module for rendering game accessories
module GameHelper
  CDN_ROOT =
    'http://media.steampowered.com/steamcommunity/public/images/apps'.freeze
  def game_icon_url(game)
    "#{CDN_ROOT}/#{game.appid}/#{game.icon_url}.jpg"
  end
end

app/views/dashboard/show.html.erb
<h1>Dashboard</h1>

<h2>What You've Been Up To</h2>

<div class="grid-row stand-out">
  <div class="grid-column">
    <h3>Latest Games</h3>

    <% @recent_library_entries.each do |library_entry| %>
      <%= render 'library_entries/blurb', { library_entry: library_entry } %>
    <% end %>
  </div>
  <div class="grid-column">
    <h3>Favorite Games</h3>

    <% @favorite_library_entries.each do |library_entry| %>
      <%= render 'library_entries/blurb', { library_entry: library_entry } %>
    <% end %>
  </div>
</div>

<h2>
  What Your Friends are Up To
  <%= link_to 'stalk someone',
              new_watched_steam_profile_path,
              class: 'action-link' %>
</h2>

<% @watched_steam_profiles.each do |watched_steam_profile| %>
  <h3>
    <%= watched_steam_profile.vanity_name %>
    <%= link_to 'unwatch', watched_steam_profile_path(watched_steam_profile),
                  class: 'action-link',
                  method: :delete,
                  data: { confirm: 'Are you sure?' }
      %>
  </h3>
  <div class="grid-row stand-out">
    <div class="grid-column">
      <h4>Recent Games</h4>
      <% watched_steam_profile.library_entries.recent.each do |library_entry| %>
        <%= render 'library_entries/blurb', { library_entry: library_entry } %>
      <% end %>
    </div>
    <div class="grid-column">
      <h4>Favorite Games</h4>
      <% watched_steam_profile.library_entries.favorites.each do |library_entry| %>
        <%= render 'library_entries/blurb', { library_entry: library_entry } %>
      <% end %>
    </div>
  </div>
<% end %>

<% if @watched_steam_profiles.count == 0 %>
  <p>Feeling a bit lonely?  Why don't you <%= link_to 'stalk some folks', new_watched_steam_profile_path %>?</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Steam Stalker</title>
    <%= csrf_meta_tags %>

    <link href='https://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Orbitron:900' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul class="header-navigation">
      <li class="logo">Steam Stalker</li>
      <% if current_user %>
          <li><%= link_to 'Dashboard', dashboard_path %></li>
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        <% end %>
      </ul>
    <div class="content-wrapper">
      <%= yield %>
    </div>
  </body>
</html>

app/views/library_entries/_blurb.html.erb
<div class="library-entry-blurb">
  <div class="header">
    <%= image_tag(game_icon_url(library_entry.game)) %>
    <span class="title">
      <%= link_to library_entry.name, library_entry.store_link, target: '_blank' %>
    </span>
    <span class="hours-played">
      <%= library_entry.playtime_in_hours %> hours
    </span>
  </div>
  <div class="playtime">
  </div>
</div>

app/views/watched_steam_profiles/new.html.erb
<h1>Add a Profile to Watch</h1>
<% if @watched_steam_profile.errors.any? %>
  <div class="notification error">
    <% @watched_steam_profile.errors.full_messages.each do |msg| %><p><%= msg %></p><% end %>
  </div>
<% end %>
<%= form_for @watched_steam_profile do |f| %>
  <%= f.label :vanity_name, class: '' %>
  <%= f.text_field :vanity_name, class: '' %>
  <input type="submit" value="Submit" class="button" />
<% end %>